version: "3.9"

services:
  admin-backend:
    container_name: admin-backend
    image: kodakcms/admin-backend:latest
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend/admin-app-backend
    ports:
      - "8080:8080"

  admin-frontend:
    container_name: admin-frontend
    image: kodakcms/admin-frontend:latest
    build:
      context: ./frontend/admin-app-frontend
    ports:
      - "8081:8081"

  db:
    image: mariadb
    container_name: admin-database
    restart: unless-stopped
    tty: true
    environment:
      MARIADB_DATABASE: "rigs_db"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    ports:
      - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10