version: "3.9"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  admin-frontend:
    container_name: admin-frontend
    build:
      context: ./frontend/admin-app-frontend
    ports:
      - "8081:8081"
    environment:
      - VIRTUAL_HOST=178.62.217.137

  admin-backend:
    container_name: admin-backend
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./backend/admin-app-backend
    ports:
      - "8080:8080"
    environment:
    - VIRTUAL_HOST=178.62.217.137:8080

  db:
    image: mariadb
    container_name: admin-database
    restart: unless-stopped
    tty: true
    environment:
      MARIADB_DATABASE: "rigs_db"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "true"
    # ports:
    #   - "3306:3306"
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10